import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import sharp from "sharp";
import type { PatternColorRow } from "@/lib/pattern-engine";
import { CHART_PAGE_LARGE, CHART_PAGE_REGULAR } from "@/lib/constants";
import { finishedSizeInches, inchesToCm, recommendedFabricCut } from "@/lib/measurements";

type ChartVariant = "regular" | "large";
type PdfDoc = InstanceType<typeof PDFDocument>;

/** Left and right text margin (inches → points). */
export const PDF_MARGIN_PT = 0.75 * 72;

/** Vertical space reserved at top of the cover page for the logo on the raster template (not used on inner pages). */
export const PDF_HEADER_RESERVED_PT = 126;

/** Space left at bottom of every page for the StitchMint footer line(s). */
export const PDF_FOOTER_RESERVED_PT = 40;

const PDF_BRAND_FOOTER =
  "This pattern was generated by StitchMint, a product of Skillbinder - crafted to bring your creativity to life.";

export type PatternPdfMeta = {
  title: string;
  fabricCount: number;
  stitchWidth: number;
  stitchHeight: number;
  totalStitches: number;
  colorCount: number;
  stitchabilityScore: number;
  difficultyLabel: string;
};

function collectPdfBuffer(doc: PdfDoc): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

export type CoverBackgroundImage = { buffer: Buffer; width: number; height: number };

function contentTextWidth(doc: PdfDoc): number {
  return doc.page.width - 2 * PDF_MARGIN_PT;
}

/**
 * Raster template for the pattern PDF cover page only (Letter); inner pages use a flat fill + drawn footer.
 * Priority: STITCHMINT_COVER_BG_PATH → public/StitchMint_Pattern_Template.jpg → pattern-cover-bg.*.
 */
export async function loadPatternCoverBackground(): Promise<CoverBackgroundImage | null> {
  const custom = process.env.STITCHMINT_COVER_BG_PATH?.trim();
  const candidates = [
    ...(custom ? [custom] : []),
    path.join(process.cwd(), "public", "StitchMint_Pattern_Template.jpg"),
    path.join(process.cwd(), "public", "pattern-cover-bg.png"),
    path.join(process.cwd(), "public", "pattern-cover-bg.jpg"),
    path.join(process.cwd(), "public", "pattern-cover-bg.webp"),
  ];
  for (const filePath of candidates) {
    try {
      if (!fs.existsSync(filePath)) continue;
      const buffer = fs.readFileSync(filePath);
      const meta = await sharp(buffer).metadata();
      if (!meta.width || !meta.height) continue;
      return { buffer, width: meta.width, height: meta.height };
    } catch {
      continue;
    }
  }
  return null;
}

function drawCoverPageBackground(doc: PdfDoc, bg: CoverBackgroundImage) {
  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const scale = Math.max(pageW / bg.width, pageH / bg.height);
  const dw = bg.width * scale;
  const dh = bg.height * scale;
  const x = (pageW - dw) / 2;
  const y = (pageH - dh) / 2;
  doc.save();
  doc.image(bg.buffer, x, y, { width: dw, height: dh });
  doc.restore();
}

/** Readable panel below the header/logo band; keeps body text off busy artwork. */
function drawTemplateBodyPanel(doc: PdfDoc) {
  const x = PDF_MARGIN_PT;
  const y = PDF_HEADER_RESERVED_PT;
  const w = doc.page.width - 2 * PDF_MARGIN_PT;
  const h = doc.page.height - y - PDF_MARGIN_PT;
  if (h < 120) return;
  doc.save();
  doc.fillOpacity(1);
  doc.fillColor("#ffffff");
  doc.roundedRect(x, y, w, h, 10).fill();
  doc.restore();
  doc.save();
  doc.strokeColor("#d8d8d8").lineWidth(0.6).roundedRect(x, y, w, h, 10).stroke();
  doc.restore();
}

function contentStartYCover(hasRasterTemplate: boolean): number {
  return hasRasterTemplate ? PDF_HEADER_RESERVED_PT + 12 : PDF_MARGIN_PT + 6;
}

function contentStartYInner(): number {
  return PDF_MARGIN_PT + 6;
}

/** Cover page only: optional full-page raster + white body panel (never call for page 2+). */
function decorateCoverLetterPage(doc: PdfDoc, bg: CoverBackgroundImage | null) {
  if (bg) {
    drawCoverPageBackground(doc, bg);
    drawTemplateBodyPanel(doc);
  } else {
    doc.save();
    doc.fillColor("#ffffff").rect(0, 0, doc.page.width, doc.page.height).fill();
    doc.restore();
  }
  doc.fillColor("#2c2416");
  doc.x = PDF_MARGIN_PT;
  doc.y = contentStartYCover(!!bg);
}

/** Inner pages: flat white fill — does not accept cover art (avoids embedding the template more than once). */
function decorateInnerLetterPage(doc: PdfDoc) {
  doc.save();
  doc.fillColor("#ffffff").rect(0, 0, doc.page.width, doc.page.height).fill();
  doc.restore();
  doc.fillColor("#2c2416");
  doc.x = PDF_MARGIN_PT;
  doc.y = contentStartYInner();
}

function drawStitchMintFooter(doc: PdfDoc) {
  const tw = contentTextWidth(doc);
  const y = doc.page.height - PDF_MARGIN_PT - PDF_FOOTER_RESERVED_PT + 4;
  doc.save();
  doc.fontSize(7.5).fillColor("#7a6f62").text(PDF_BRAND_FOOTER, PDF_MARGIN_PT, y, {
    width: tw,
    align: "center",
    lineGap: 1,
  });
  doc.restore();
}

/** Finishes the current page with the brand footer, then starts a new Letter page (never draws cover raster). */
function addDecoratedLetterPage(doc: PdfDoc) {
  drawStitchMintFooter(doc);
  doc.addPage({ size: "LETTER", margin: 0 });
  decorateInnerLetterPage(doc);
}

function drawCover(
  doc: PdfDoc,
  meta: PatternPdfMeta,
  opts: { original?: Buffer; preview: Buffer },
  chartVariant: ChartVariant,
) {
  const tw = contentTextWidth(doc);
  const { widthIn, heightIn } = finishedSizeInches(meta.stitchWidth, meta.stitchHeight, meta.fabricCount);
  const cut = recommendedFabricCut(widthIn, heightIn);

  doc.fontSize(22).fillColor("#2c2416").text("StitchMint Pattern", PDF_MARGIN_PT, doc.y, {
    width: tw,
    align: "left",
  });
  doc.moveDown(0.35);
  const bandH = 28;
  const bandX = PDF_MARGIN_PT;
  const bandY = doc.y;
  const bandBg = chartVariant === "large" ? "#6b3f1a" : "#1e3a5f";
  const bandLabel = chartVariant === "large" ? "LARGE-PRINT CHART PDF" : "REGULAR CHART PDF";
  doc.save();
  doc.fillColor(bandBg).roundedRect(bandX, bandY, tw, bandH, 5).fill();
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#ffffff").text(bandLabel, bandX, bandY + 8, {
    width: tw,
    align: "center",
  });
  doc.restore();
  doc.font("Helvetica");
  doc.y = bandY + bandH + 10;
  doc.x = PDF_MARGIN_PT;
  doc.fontSize(9).fillColor("#5c5346").text(
    chartVariant === "large"
      ? "Companion file in your ZIP: Pattern-Regular.pdf (same grid, smaller symbols, fewer chart pages)."
      : "Companion file in your ZIP: Pattern-Large-Print.pdf (same grid, larger symbols, more chart pages).",
    { width: tw, align: "left" },
  );
  doc.moveDown(0.45);
  doc.fontSize(16).fillColor("#2c2416").text(meta.title, { width: tw, align: "left" });
  doc.moveDown(0.9);

  const thumbW = 138;
  const gap = 20;
  const y = doc.y;
  const startX = PDF_MARGIN_PT;

  if (opts.original) {
    try {
      doc.image(opts.original, startX, y, { width: thumbW, height: thumbW, fit: [thumbW, thumbW], align: "center" });
    } catch {
      doc.rect(startX, y, thumbW, thumbW).stroke("#d8cfc0");
    }
  } else {
    doc.rect(startX, y, thumbW, thumbW).stroke("#d8cfc0");
  }
  doc.fontSize(9).fillColor("#5c5346").text("Your photo", startX, y + thumbW + 6, { width: thumbW, align: "left" });

  try {
    doc.image(opts.preview, startX + thumbW + gap, y, {
      width: thumbW,
      height: thumbW,
      fit: [thumbW, thumbW],
      align: "center",
    });
  } catch {
    doc.rect(startX + thumbW + gap, y, thumbW, thumbW).stroke("#d8cfc0");
  }
  doc.fontSize(9).text("Stitched preview", startX + thumbW + gap, y + thumbW + 6, { width: thumbW, align: "left" });

  doc.y = y + thumbW + 36;
  doc.x = PDF_MARGIN_PT;
  doc.moveDown(0.5);
  doc.fontSize(11).fillColor("#2c2416");
  doc.text(`Grid: ${meta.stitchWidth} × ${meta.stitchHeight} stitches`, { width: tw, align: "left" });
  const slice = chartVariant === "large" ? CHART_PAGE_LARGE : CHART_PAGE_REGULAR;
  const printLabel = chartVariant === "large" ? "Large-print chart" : "Regular chart";
  const sliceExplain =
    chartVariant === "large"
      ? `${printLabel}: each printed sheet shows up to ${slice.cols} × ${slice.rows} stitches from this same grid (${slice.overlap}-stitch overlap between sheets). Fewer stitches per page → larger printed symbols and more chart pages. The embroidery is not finer or “higher detail” — it is the same chart, zoomed for reading.`
      : `${printLabel}: each printed sheet shows up to ${slice.cols} × ${slice.rows} stitches from this same grid (${slice.overlap}-stitch overlap between sheets). More stitches per page → smaller printed symbols and fewer chart pages. Same chart as the large-print PDF — not less detail in the stitch design.`;
  doc.fontSize(9).fillColor("#5c5346").text(sliceExplain, { width: tw, align: "left" });
  doc.moveDown(0.35);
  doc.fontSize(11).fillColor("#2c2416");
  doc.text(`Fabric: ${meta.fabricCount}-count Aida`, { width: tw, align: "left" });
  doc.text(
    `Finished size: ${widthIn.toFixed(2)} in × ${heightIn.toFixed(2)} in (${inchesToCm(widthIn).toFixed(1)} × ${inchesToCm(heightIn).toFixed(1)} cm)`,
    { width: tw, align: "left" },
  );
  doc.text(`Suggested fabric cut (includes margin): about ${cut.widthIn} in × ${cut.heightIn} in`, { width: tw, align: "left" });
  doc.text(`DMC colors in chart: ${meta.colorCount}`, { width: tw, align: "left" });
  doc.text(`Estimated total stitches: ${meta.totalStitches.toLocaleString()}`, { width: tw, align: "left" });
  doc.text(`Stitchability score: ${meta.stitchabilityScore}/100 (${meta.difficultyLabel})`, { width: tw, align: "left" });
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor("#6b5f52");
  doc.text(
    "This chart is an artistic interpretation. Thread colors are matched to DMC shades; results vary with fabric, dye lots, lighting, and technique.",
    { width: tw, align: "left" },
  );
  doc.moveDown(0.45);
  doc.text("© StitchMint. Personal use only unless a commercial license is purchased separately.", {
    width: tw,
    align: "left",
  });
}

function drawInstructions(doc: PdfDoc) {
  addDecoratedLetterPage(doc);
  const tw = contentTextWidth(doc);
  doc.fontSize(18).fillColor("#2c2416").text("How to use your chart", PDF_MARGIN_PT, doc.y, { width: tw, align: "left" });
  doc.moveDown(0.55);
  doc.fontSize(11).fillColor("#3a3228");
  const blocks = [
    "Fabric count tells you how many stitches fit in one inch. Higher counts mean smaller stitches and a smaller finished piece for the same chart.",
    "Each square on the chart is one cross stitch. Follow the row and column guides along the edges.",
    "Symbols inside each square tell you which thread color to use. Match the symbol to the legend.",
    "Start from the center of your fabric unless you prefer another starting point. Many stitchers grid their fabric lightly with a washable pen.",
    "Use the thread legend for shopping. Always compare floss at the shop when possible—dye lots vary.",
    "Before you buy supplies, double-check colors against the legend in good lighting.",
  ];
  for (const b of blocks) {
    doc.text(b, { width: tw, align: "left" });
    doc.moveDown(0.55);
  }
}

function drawLegend(doc: PdfDoc, palette: PatternColorRow[]) {
  addDecoratedLetterPage(doc);
  const tw = contentTextWidth(doc);
  const left = PDF_MARGIN_PT;
  doc.fontSize(18).fillColor("#2c2416").text("Thread legend", left, doc.y, { width: tw, align: "left" });
  doc.moveDown(0.65);
  let y = doc.y;
  const rowH = 22;
  doc.fontSize(10);
  const colSym = left;
  const colDmc = left + 44;
  const colName = left + 96;
  const colSt = left + tw - 108;
  const colSk = left + tw - 52;
  doc.text("Symbol", colSym, y, { width: 40, align: "left" });
  doc.text("DMC", colDmc, y, { width: 44, align: "left" });
  doc.text("Name", colName, y, { width: Math.max(100, colSt - colName - 8), align: "left" });
  doc.text("Stitches", colSt, y, { width: 56, align: "left" });
  doc.text("Skeins*", colSk, y, { width: 48, align: "left" });
  y += rowH;
  doc.moveTo(left, y).lineTo(left + tw, y).stroke("#d8cfc0");
  y += 8;
  const pageBottom = doc.page.height - PDF_MARGIN_PT - PDF_FOOTER_RESERVED_PT;
  for (const row of palette) {
    if (y > pageBottom - rowH) {
      addDecoratedLetterPage(doc);
      y = doc.y;
    }
    doc.save();
    doc.fillColor(`#${row.hex}`).rect(colSym, y - 2, 16, 16).fill();
    doc.strokeColor("#c9bfb0").rect(colSym, y - 2, 16, 16).stroke();
    doc.restore();
    doc.fillColor("#2c2416").fontSize(10).text(row.symbol, colSym + 22, y, { width: 36, align: "left" });
    doc.text(row.dmcNumber, colDmc, y, { width: 44, align: "left" });
    doc.text(row.dmcName, colName, y, { width: Math.max(100, colSt - colName - 8), align: "left" });
    doc.text(String(row.stitchCount), colSt, y, { width: 56, align: "left" });
    doc.text(String(row.estimatedSkeins), colSk, y, { width: 48, align: "left" });
    y += rowH;
  }
  doc.y = y;
  doc.x = left;
  doc.moveDown(0.6);
  doc.fontSize(8).fillColor("#6b5f52").text("*Skein estimates are approximate.", { width: tw, align: "left" });
}

function drawChartPages(doc: PdfDoc, grid: number[][], palette: PatternColorRow[], variant: ChartVariant) {
  const H = grid.length;
  const W = grid[0]?.length ?? 0;
  const cfg = variant === "large" ? CHART_PAGE_LARGE : CHART_PAGE_REGULAR;
  const PW = cfg.cols;
  const PH = cfg.rows;
  const O = cfg.overlap;
  const marginL = PDF_MARGIN_PT;
  const marginR = PDF_MARGIN_PT;
  const marginB = PDF_MARGIN_PT + PDF_FOOTER_RESERVED_PT;
  const labelCol = variant === "large" ? 34 : 28;
  const labelRow = variant === "large" ? 26 : 22;
  const chartTitleH = 16;
  const chartTop = PDF_MARGIN_PT + 4;
  const topBand = chartTop + chartTitleH;
  const originX = marginL + labelCol;
  const originY = topBand + labelRow;
  const usableW = doc.page.width - marginL - marginR - labelCol;
  const usableH = doc.page.height - originY - marginB;
  const cell = Math.min(variant === "large" ? 12 : 8, Math.floor(Math.min(usableW / PW, usableH / PH)));

  let pageIndex = 0;
  for (let startY = 0; startY < H; startY += PH - O) {
    for (let startX = 0; startX < W; startX += PW - O) {
      pageIndex++;
      addDecoratedLetterPage(doc);

      const tw = contentTextWidth(doc);
      doc.fontSize(10).fillColor("#5c5346").text(
        `Chart ${pageIndex} — rows ${startY + 1}–${Math.min(H, startY + PH)}`,
        marginL,
        chartTop,
        { width: tw, align: "left" },
      );

      // Column guides (every 10)
      doc.save();
      doc.fontSize(variant === "large" ? 7 : 6).fillColor("#7a6f62");
      for (let c = 0; c < PW && startX + c < W; c++) {
        const gx = originX + c * cell;
        const colNum = startX + c + 1;
        if (colNum % 10 === 1 || colNum % 10 === 0) {
          doc.text(String(colNum), gx, originY - 14, { width: cell, align: "center" });
        }
      }
      doc.restore();

      for (let r = 0; r < PH && startY + r < H; r++) {
        const rowNum = startY + r + 1;
        if (rowNum % 10 === 1 || rowNum % 10 === 0) {
          doc.fontSize(variant === "large" ? 7 : 6).fillColor("#7a6f62").text(String(rowNum), marginL, originY + r * cell + cell * 0.35, {
            width: labelCol - 6,
            align: "right",
          });
        }
        for (let c = 0; c < PW && startX + c < W; c++) {
          const idx = grid[startY + r]![startX + c]!;
          const col = palette[idx]!;
          const gx = originX + c * cell;
          const gy = originY + r * cell;
          const isOverlapCol = c < O && startX > 0;
          const isOverlapRow = r < O && startY > 0;
          const overlap = isOverlapCol || isOverlapRow;
          doc.save();
          doc.lineWidth(overlap ? 0.85 : 0.35);
          doc.strokeColor(overlap ? "#c49a6c" : "#e3d9cf");
          doc.fillColor("#ffffff").rect(gx, gy, cell, cell).fill();
          doc.rect(gx, gy, cell, cell).stroke();
          doc.restore();
          doc.fillColor("#1f1a14").fontSize(variant === "large" ? 8 : 5.5).text(col.symbol, gx, gy + cell * 0.28, {
            width: cell,
            align: "center",
          });
        }
      }

      doc.fontSize(8).fillColor("#9a8f82").text("Overlap pages using shaded border columns/rows when present.", marginL, doc.page.height - PDF_MARGIN_PT - PDF_FOOTER_RESERVED_PT - 16, {
        width: tw,
        align: "left",
      });
    }
  }
}

export async function buildPatternPdf(params: {
  meta: PatternPdfMeta;
  grid: number[][];
  palette: PatternColorRow[];
  variant: ChartVariant;
  originalImage?: Buffer;
  previewImage: Buffer;
  /** When omitted, loads once from public / env (see loadPatternCoverBackground). */
  coverBackground?: CoverBackgroundImage | null;
}): Promise<Buffer> {
  const doc = new PDFDocument({ size: "LETTER", margin: 0, bufferPages: false });
  const done = collectPdfBuffer(doc);

  const coverBg =
    params.coverBackground !== undefined ? params.coverBackground : await loadPatternCoverBackground();

  decorateCoverLetterPage(doc, coverBg);
  drawCover(doc, params.meta, { original: params.originalImage, preview: params.previewImage }, params.variant);
  drawInstructions(doc);
  drawLegend(doc, params.palette);
  drawChartPages(doc, params.grid, params.palette, params.variant);
  drawStitchMintFooter(doc);

  doc.end();
  return done;
}

export async function buildThreadShoppingListPdf(
  palette: PatternColorRow[],
  coverBackground?: CoverBackgroundImage | null,
): Promise<Buffer> {
  const bg = coverBackground !== undefined ? coverBackground : await loadPatternCoverBackground();
  const doc = new PDFDocument({ size: "LETTER", margin: 0, bufferPages: false });
  const done = collectPdfBuffer(doc);
  decorateCoverLetterPage(doc, bg);
  const tw = contentTextWidth(doc);
  const left = PDF_MARGIN_PT;

  doc.fontSize(20).fillColor("#2c2416").text("Thread shopping list", left, doc.y, { width: tw, align: "left" });
  doc.moveDown(0.45);
  doc.fontSize(10).fillColor("#5c5346").text("DMC Six-Strand Embroidery Floss — check colors in store when possible.", {
    width: tw,
    align: "left",
  });
  doc.moveDown(0.85);
  let y = doc.y;
  const colCh = left;
  const colDmc = left + 28;
  const colName = left + 92;
  const colSk = left + tw - 56;
  doc.fontSize(10).text("☐", colCh, y, { width: 20, align: "left" });
  doc.text("DMC", colDmc, y, { width: 52, align: "left" });
  doc.text("Color name", colName, y, { width: Math.max(160, colSk - colName - 10), align: "left" });
  doc.text("Skeins (est.)", colSk, y, { width: 52, align: "left" });
  y += 22;
  doc.moveTo(left, y).lineTo(left + tw, y).stroke("#d8cfc0");
  y += 10;
  const pageBottom = doc.page.height - PDF_MARGIN_PT - PDF_FOOTER_RESERVED_PT;
  for (const row of palette) {
    if (y > pageBottom - 28) {
      addDecoratedLetterPage(doc);
      y = doc.y;
    }
    doc.rect(colCh, y - 2, 14, 14).fill(`#${row.hex}`).stroke("#c9bfb0");
    doc.fillColor("#2c2416").text("☐", colCh + 18, y, { width: 20, align: "left" });
    doc.text(row.dmcNumber, colDmc, y, { width: 52, align: "left" });
    doc.text(row.dmcName, colName, y, { width: Math.max(140, colSk - colName - 12), align: "left" });
    doc.text(String(row.estimatedSkeins), colSk, y, { width: 52, align: "left" });
    y += 22;
  }
  drawStitchMintFooter(doc);
  doc.end();
  return done;
}

export async function buildReadMeFirstPdf(coverBackground?: CoverBackgroundImage | null): Promise<Buffer> {
  const bg = coverBackground !== undefined ? coverBackground : await loadPatternCoverBackground();
  const doc = new PDFDocument({ size: "LETTER", margin: 0, bufferPages: false });
  const done = collectPdfBuffer(doc);
  decorateCoverLetterPage(doc, bg);
  const tw = contentTextWidth(doc);
  const left = PDF_MARGIN_PT;

  doc.fontSize(20).fillColor("#2c2416").text("Read me first", left, doc.y, { width: tw, align: "left" });
  doc.moveDown(0.55);
  doc.fontSize(11).fillColor("#3a3228");
  const sections = [
    "Printing: print chart pages at 100% scale. Do not shrink to fit unless a page overflows—if it does, split across prints carefully.",
    "Reading the chart: each square is one full cross stitch. Use the legend to match symbols to DMC colors.",
    "Fabric: Aida is beginner-friendly. Your pattern notes the count you selected.",
    "Needle: a size 24 tapestry needle is a common choice for 14–18 count Aida.",
    "Disclaimer: your finished piece will reflect your fabric, floss dye lots, lighting, and stitching style. This chart is a guide, not a guarantee.",
    `Questions: ${process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? "support@skillbinder.com"}`,
  ];
  for (const s of sections) {
    doc.text(s, { width: tw, align: "left" });
    doc.moveDown(0.75);
  }
  drawStitchMintFooter(doc);
  doc.end();
  return done;
}
